/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itcr.barbershop.GUI;

/**
 *
 * @author Samantha
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ButtonAppointment = new javax.swing.JButton();
        buttonCustomer = new javax.swing.JButton();
        buttonWaitingList = new javax.swing.JButton();
        title = new java.awt.Label();
        buttonServiceType = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(210, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 250, 500));

        ButtonAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itcr/barbershop/GUI/InterfaceImages/InterfaceImages/calendar-star.png"))); // NOI18N
        ButtonAppointment.setText("Citas");
        background.add(ButtonAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 150, 150));

        buttonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itcr/barbershop/GUI/InterfaceImages/InterfaceImages/user.png"))); // NOI18N
        buttonCustomer.setText("Clientes");
        buttonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerActionPerformed(evt);
            }
        });
        background.add(buttonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 140, 150));

        buttonWaitingList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itcr/barbershop/GUI/InterfaceImages/InterfaceImages/queue-alt.png"))); // NOI18N
        buttonWaitingList.setText("Lista De Espera");
        buttonWaitingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWaitingListActionPerformed(evt);
            }
        });
        background.add(buttonWaitingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 150, 150));

        title.setAlignment(java.awt.Label.CENTER);
        title.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        title.setForeground(new java.awt.Color(235, 51, 51));
        title.setMaximumSize(new java.awt.Dimension(33567, 32767));
        title.setPreferredSize(new java.awt.Dimension(200, 50));
        title.setText("BarberShop");
        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 210, 90));

        buttonServiceType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itcr/barbershop/GUI/InterfaceImages/InterfaceImages/barber-shop.png"))); // NOI18N
        buttonServiceType.setText("Servicios");
        background.add(buttonServiceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCustomerActionPerformed

    private void buttonWaitingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWaitingListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonWaitingListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAppointment;
    private javax.swing.JPanel background;
    private javax.swing.JButton buttonCustomer;
    private javax.swing.JButton buttonServiceType;
    private javax.swing.JButton buttonWaitingList;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label title;
    // End of variables declaration//GEN-END:variables
}
